services:
    - type: web
      name: pickle-os-game-store
      runtime: node
      plan: free
      rootDir: .
      buildCommand: npm install
      startCommand: npm start
      autoDeploy: true
      envVars:
          - key: NODE_VERSION
            value: 20
